# -*- coding: utf-8 -*-
"""Basic_2_OOP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1071jkQ06QLKxVtEYJylYx0CNC6jka4XC

# Section1
"""

class ATM:
    pass

from random import randint

class ATM:
    def __init__(self, account_name, bank_name, initial): ## double underscore เรียกว่า dunder
        self.account_name = account_name
        self.bank_name = bank_name
        self.balance = initial

    ## string representation
    def __str__(self):
        return f"This is an account of {self.account_name}, bank: {self.bank_name}"

    ## method => function
    def check_balance(self):
        print(f"Balance: {self.balance}")

    def deposit(self, money):
        self.balance += money
        print(f"Deposit successfully: your name balance: {self.balance} THB")

    def withdraw(self, money):
        self.balance -= money
        print(f"Withdraw successfully: your name balance: {self.balance} THB")

    def get_OTP(self):
        otp = randint(1000,9999)
        print(f"Your OTP: {otp}. This OTP will be available in the next 2 minutes.")

# create an instance from ATM class
# instance ประมาณว่า cookie ที่เราสร้างขึ้นมา ก็คือ acc1
# instace = object
acc1 = ATM("toy", "scb", 500)

acc1.bank_name

acc1

# code is for human
print(acc1)

acc1.check_balance()

acc1.deposit(1000)

acc1.withdraw(200)

import random

random.randint(1000,9999)

acc1.get_OTP()

"""# Section2

## Try Except Block
"""

try:
    1/0
except ZeroDivisionError:
    print("cannot divide by zero")
except NameError:
    print("variable not defined")
else:
    print("Done")
finally: # Run เสมอ
    print("Complete!")

## import csv
import csv

# แบบเก่า
try:
    file = open("friend.csv")

    data = csv.reader(file)

    for row in data:
        print(row)

    file.close()
except FileNotFoundError:
    print("File not found.")

## context manager
result = []

## open and close file automatically
try:
    with open("friend.csv", "r") as file:
        data = csv.reader(file)
        for row in data:
            result.append(row)
except:
    print("file not found")
else:
    print("load data successfully!")
finally:
    print(result)

"""## Command Line and Pandas"""

## command line
!pwd

!cat friend.csv

# make folder
!mkdir cat

!rmdir cat

## import csv (data analyst style)
import pandas as pd

pd.read_csv("friend.csv")

try:
    df = pd.read_csv("friend.csv")
except:
    print("a little error.")

df

## write csv file using pandas
df.to_csv("newCSVFile.csv")

!ls

## write csv using csv module
## เก่า

import csv

col_names = ["id", "food", "price"]

data = [
    [1, "pizza", 200],
    [2, "rice", 20]
]

with open("foods.csv", "w") as file:
    writer = csv.writer(file)
    writer.writerow(col_names)
    writer.writerows(data)

!cat food.csv