# -*- coding: utf-8 -*-
"""Basic_1_Foundation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lV_jPWOW0O875alR7nxSEG-9-r2fsxl7

# **Programming Foundation**
- variable
- data type
- data structure
- function
- control flow
"""

5**2 # 5*5

# comment
# note to this code cell
print("Hello World")

1+2

"""## **Variables**"""

income <- 35000
expense <- 25000
saving <- income - expense

print(saving)

print(income)

# create new variable
"Sun" -> my_name
my_name <- "Sam"
print(my_name)

# remove variable
rm(my_name)

# save income for 10 years, interest rate 5%

income = 100000
income * ((1+0.05) ** 20)

"""# **Data Types**
  
- numeric
- character (text,string)
- logical (TRUE, FALSE)
- date
- factor (categorical - stats, special in R)
"""

# numeric
gpa <- 3.41
print(gpa)
print(class(gpa))

## character
class("hello world")

## concat two character
paste0("hello", "world")
paste("hello", "world")

## boolean
class(F)
class(T)
1+1 == 2
5 != 5
!FALSE
!(1+1 == 2)
"hi" == "Hi"

## date
today_date <- as.Date("2023-11-11")
print(today_date)
print(class(today_date))

## as.___() change data type
as.character(today_date)
as.integer(FALSE)

## vector => similar to Google Sheets Array
gender <- c("male", "female", "male") # ซ้ำกันได้

gender_new <- factor(gender) # จำแนก
gender_new
class(gender_new)

is.factor(gender_new) ## check
class(gender_new)

## factor has two categories
## 1. nominal: male, female
## 2. ordinal: low < med < high

m1 <- matrix(c(3,2,1,4,2,4), nrow = 2   )
print(m1)